
import { ExamDataPoint, Category, Trend } from './types';

export const EXAM_DATA: ExamDataPoint[] = [
  // --- LIPIDOGRAMA ---
  {
    id: 'chol_total',
    name: 'Colesterol Total',
    unit: 'mg/dL',
    reference: '< 190',
    date1: '17/09/2025',
    value1: 237,
    status1: 'Alto',
    date2: '02/12/2025',
    value2: 218,
    status2: 'Alto',
    observation: 'Melhorou um pouco, mas continua alto',
    category: Category.LIPID,
    trend: Trend.IMPROVED
  },
  {
    id: 'ldl',
    name: 'LDL-c',
    unit: 'mg/dL',
    reference: '< 130',
    date1: '17/09/2025',
    value1: 153,
    status1: 'Alto',
    date2: '02/12/2025',
    value2: 153,
    status2: 'Alto',
    observation: 'Praticamente igual, continua alto',
    category: Category.LIPID,
    trend: Trend.STABLE
  },
  {
    id: 'hdl',
    name: 'HDL-c',
    unit: 'mg/dL',
    reference: '> 40',
    date1: '17/09/2025',
    value1: 40,
    status1: 'Limítrofe',
    date2: '02/12/2025',
    value2: 36,
    status2: 'Baixo',
    observation: 'Piorou um pouco (HDL mais baixo)',
    category: Category.LIPID,
    trend: Trend.WORSENED
  },
  {
    id: 'trig',
    name: 'Triglicerídeos',
    unit: 'mg/dL',
    reference: '< 150',
    date1: '17/09/2025',
    value1: 219,
    status1: 'Alto',
    date2: '02/12/2025',
    value2: 147,
    status2: 'Normal',
    observation: 'Melhorou e normalizou',
    category: Category.LIPID,
    trend: Trend.IMPROVED
  },
  {
    id: 'vldl',
    name: 'VLDL-c',
    unit: 'mg/dL',
    reference: '< 30',
    date1: '17/09/2025',
    value1: 44,
    status1: 'Alto',
    date2: '02/12/2025',
    value2: 29,
    status2: 'Normal',
    observation: 'Normalizou',
    category: Category.LIPID,
    trend: Trend.IMPROVED
  },

  // --- HEPÁTICO ---
  {
    id: 'ggt',
    name: 'Gama-GT',
    unit: 'U/L',
    reference: '9–36',
    date1: '17/09/2025',
    value1: 190,
    status1: 'Alto',
    date2: '02/12/2025',
    value2: 69,
    status2: 'Alto',
    observation: 'Caiu bastante, mas ainda acima do normal',
    category: Category.LIVER,
    trend: Trend.IMPROVED
  },
  {
    id: 'tgo',
    name: 'TGO/AST',
    unit: 'U/L',
    reference: '5–34',
    date1: '17/09/2025',
    value1: 65,
    status1: 'Alto',
    date2: '02/12/2025',
    value2: 40,
    status2: 'Alto',
    observation: 'Melhorou, mas segue discretamente elevado',
    category: Category.LIVER,
    trend: Trend.IMPROVED
  },
  {
    id: 'tgp',
    name: 'TGP/ALT',
    unit: 'U/L',
    reference: '0–55',
    date1: '17/09/2025',
    value1: 59,
    status1: 'Alto',
    date2: '02/12/2025',
    value2: 23,
    status2: 'Normal',
    observation: 'Normalizou',
    category: Category.LIVER,
    trend: Trend.IMPROVED
  },
  {
    id: 'fosf_alc',
    name: 'Fosfatase Alcalina',
    unit: 'U/L',
    reference: '40–150',
    date1: '17/09/2025',
    value1: 132,
    status1: 'Normal',
    date2: '02/12/2025',
    value2: 102,
    status2: 'Normal',
    observation: 'Normal nos dois exames',
    category: Category.LIVER,
    trend: Trend.STABLE
  },
  {
    id: 'bilirrubina_tot',
    name: 'Bilirrubina Total',
    unit: 'mg/dL',
    reference: '0.20-1.20',
    date1: '17/09/2025',
    value1: 0.50,
    status1: 'Normal',
    date2: '02/12/2025',
    value2: 0.50,
    status2: 'Normal',
    observation: 'Estável e normal',
    category: Category.LIVER,
    trend: Trend.STABLE
  },
  {
    id: 'bilirrubina_dir',
    name: 'Bilirrubina Direta',
    unit: 'mg/dL',
    reference: '0.00-0.50',
    date1: '17/09/2025',
    value1: 0.15,
    status1: 'Normal',
    date2: '02/12/2025',
    value2: 0.22,
    status2: 'Normal',
    observation: 'Estável e normal',
    category: Category.LIVER,
    trend: Trend.STABLE
  },

  // --- METABÓLICO / OUTROS ---
  {
    id: 'glic',
    name: 'Glicemia',
    unit: 'mg/dL',
    reference: '74–99',
    date1: '17/09/2025',
    value1: 131,
    status1: 'Alta',
    date2: '02/12/2025',
    value2: 82,
    status2: 'Normal',
    observation: 'Melhorou e normalizou',
    category: Category.METABOLIC,
    trend: Trend.IMPROVED
  },
  {
    id: 'amilase',
    name: 'Amilase',
    unit: 'U/L',
    reference: '28–100',
    date1: '17/09/2025',
    value1: 58,
    status1: 'Normal',
    date2: '02/12/2025',
    value2: 49,
    status2: 'Normal',
    observation: 'Normal nos dois exames',
    category: Category.METABOLIC,
    trend: Trend.STABLE
  },
  {
    id: 'dhl',
    name: 'DHL (Lactato Desidrog.)',
    unit: 'U/L',
    reference: '125–220',
    date1: '17/09/2025',
    value1: 213,
    status1: 'Normal',
    date2: '02/12/2025',
    value2: 147,
    status2: 'Normal',
    observation: 'Normal. Redução dentro da faixa',
    category: Category.METABOLIC,
    trend: Trend.STABLE
  },
  {
    id: 'prot_totais',
    name: 'Proteínas Totais',
    unit: 'g/dL',
    reference: '6.4–8.3',
    date1: '17/09/2025',
    value1: 7.1,
    status1: 'Normal',
    date2: '02/12/2025',
    value2: 7.1,
    status2: 'Normal',
    observation: 'Estável',
    category: Category.METABOLIC,
    trend: Trend.STABLE
  },

  // --- RENAL ---
  {
    id: 'creatinina',
    name: 'Creatinina',
    unit: 'mg/dL',
    reference: '0.50–1.10',
    date1: '17/09/2025',
    value1: 0.58,
    status1: 'Normal',
    date2: '02/12/2025',
    value2: 0.66,
    status2: 'Normal',
    observation: 'Função renal preservada',
    category: Category.RENAL,
    trend: Trend.STABLE
  },
  {
    id: 'ureia',
    name: 'Ureia',
    unit: 'mg/dL',
    reference: '15–40',
    date1: '17/09/2025',
    value1: 20,
    status1: 'Normal',
    date2: '02/12/2025',
    value2: 15,
    status2: 'Normal (Lim. Inf)',
    observation: 'Normal nos dois exames',
    category: Category.RENAL,
    trend: Trend.STABLE
  },
  {
    id: 'acido_urico',
    name: 'Ácido Úrico',
    unit: 'mg/dL',
    reference: '2.5–6.2',
    date1: '17/09/2025',
    value1: 6.1,
    status1: 'Normal (Lim. Sup)',
    date2: '02/12/2025',
    value2: 5.7,
    status2: 'Normal',
    observation: 'Melhorou (reduziu)',
    category: Category.RENAL,
    trend: Trend.IMPROVED
  },

  // --- ELETRÓLITOS ---
  {
    id: 'cloreto',
    name: 'Cloreto',
    unit: 'mmol/L',
    reference: '98–107',
    date1: '17/09/2025',
    value1: 108,
    status1: 'Alto',
    date2: '02/12/2025',
    value2: 109,
    status2: 'Alto',
    observation: 'Continua discretamente acima',
    category: Category.ELECTROLYTES,
    trend: Trend.STABLE
  },
  {
    id: 'sodio',
    name: 'Sódio',
    unit: 'mmol/L',
    reference: '136–145',
    date1: '17/09/2025',
    value1: 139,
    status1: 'Normal',
    date2: '02/12/2025',
    value2: 141,
    status2: 'Normal',
    observation: 'Estável e normal',
    category: Category.ELECTROLYTES,
    trend: Trend.STABLE
  },
  {
    id: 'potassio',
    name: 'Potássio',
    unit: 'mmol/L',
    reference: '3.5–5.1',
    date1: '17/09/2025',
    value1: 4.3,
    status1: 'Normal',
    date2: '02/12/2025',
    value2: 4.0,
    status2: 'Normal',
    observation: 'Estável e normal',
    category: Category.ELECTROLYTES,
    trend: Trend.STABLE
  },
  {
    id: 'calcio',
    name: 'Cálcio',
    unit: 'mg/dL',
    reference: '8.4–10.2',
    date1: '17/09/2025',
    value1: 9.2,
    status1: 'Normal',
    date2: '02/12/2025',
    value2: 9.9,
    status2: 'Normal',
    observation: 'Normal',
    category: Category.ELECTROLYTES,
    trend: Trend.STABLE
  },
  {
    id: 'fosforo',
    name: 'Fósforo',
    unit: 'mg/dL',
    reference: '2.3–4.7',
    date1: '17/09/2025',
    value1: 4.1,
    status1: 'Normal',
    date2: '02/12/2025',
    value2: 3.8,
    status2: 'Normal',
    observation: 'Normal',
    category: Category.ELECTROLYTES,
    trend: Trend.STABLE
  },

  // --- MUSCULAR / INFLAMATÓRIO ---
  {
    id: 'cpk',
    name: 'CPK',
    unit: 'U/L',
    reference: '29–168',
    date1: '17/09/2025',
    value1: 42,
    status1: 'Normal',
    date2: '02/12/2025',
    value2: 1219,
    status2: 'Muito Alto',
    observation: 'Piorou muito: passou de normal para bem elevado (lesão muscular)',
    category: Category.MUSCLE,
    trend: Trend.WORSENED
  },
  {
    id: 'pcr',
    name: 'Proteína C reativa',
    unit: 'mg/dL',
    reference: '< 0,5',
    date1: '17/09/2025',
    value1: 1.86,
    status1: 'Alta',
    date2: null,
    value2: null,
    status2: 'N/A',
    observation: 'Em setembro estava aumentada; em dezembro não foi medida',
    category: Category.INFLAMMATION,
    trend: Trend.UNKNOWN
  },

  // --- HEMATOLOGIA (Dez only mostly) ---
  {
    id: 'ferro',
    name: 'Ferro Sérico',
    unit: 'mcg/dL',
    reference: '50–170',
    date1: '17/09/2025',
    value1: null,
    status1: 'N/A',
    date2: '02/12/2025',
    value2: 44,
    status2: 'Baixo',
    observation: 'Ferro baixo em Dezembro. Atenção para anemia.',
    category: Category.HEMATOLOGY,
    trend: Trend.UNKNOWN
  },
  {
    id: 'hemoglobina',
    name: 'Hemoglobina',
    unit: 'g/dL',
    reference: '12.0–15.5',
    date1: '17/09/2025',
    value1: null,
    status1: 'N/A',
    date2: '02/12/2025',
    value2: 14.2,
    status2: 'Normal',
    observation: 'Normal em Dezembro',
    category: Category.HEMATOLOGY,
    trend: Trend.UNKNOWN
  },
  {
    id: 'hemacias',
    name: 'Hemácias',
    unit: 'x10^6/µL',
    reference: '3.90–5.00',
    date1: '17/09/2025',
    value1: null,
    status1: 'N/A',
    date2: '02/12/2025',
    value2: 5.40,
    status2: 'Alto',
    observation: 'Levemente aumentado em Dezembro',
    category: Category.HEMATOLOGY,
    trend: Trend.UNKNOWN
  },
  {
    id: 'hematocrito',
    name: 'Hematócrito',
    unit: '%',
    reference: '35.0–45.0',
    date1: '17/09/2025',
    value1: null,
    status1: 'N/A',
    date2: '02/12/2025',
    value2: 42.0,
    status2: 'Normal',
    observation: 'Normal em Dezembro',
    category: Category.HEMATOLOGY,
    trend: Trend.UNKNOWN
  },
  {
    id: 'leucocitos',
    name: 'Leucócitos Totais',
    unit: 'x10^3/µL',
    reference: '3.5–10.5',
    date1: '17/09/2025',
    value1: null,
    status1: 'N/A',
    date2: '02/12/2025',
    value2: 6.9,
    status2: 'Normal',
    observation: 'Normal em Dezembro',
    category: Category.HEMATOLOGY,
    trend: Trend.UNKNOWN
  },
  {
    id: 'plaquetas',
    name: 'Plaquetas',
    unit: 'x10^3/µL',
    reference: '150–450',
    date1: '17/09/2025',
    value1: null,
    status1: 'N/A',
    date2: '02/12/2025',
    value2: 273,
    status2: 'Normal',
    observation: 'Normal em Dezembro',
    category: Category.HEMATOLOGY,
    trend: Trend.UNKNOWN
  },

  // --- URINA (Dez only) ---
  {
    id: 'urina_cultura',
    name: 'Urocultura',
    unit: '',
    reference: 'Negativo',
    date1: '17/09/2025',
    value1: null,
    status1: 'N/A',
    date2: '02/12/2025',
    value2: 'Positivo',
    status2: 'Infecção',
    observation: 'Positivo para E. Coli (>100.000 col/mL). Infecção Urinária.',
    category: Category.URINE,
    trend: Trend.WORSENED
  },
  {
    id: 'urina_leucocitos',
    name: 'Urina - Leucócitos',
    unit: 'uL',
    reference: '0–13',
    date1: '17/09/2025',
    value1: null,
    status1: 'N/A',
    date2: '02/12/2025',
    value2: 24,
    status2: 'Alto',
    observation: 'Piúria (leucócitos na urina) indicando inflamação/infecção',
    category: Category.URINE,
    trend: Trend.WORSENED
  },
  {
    id: 'urina_hemacias',
    name: 'Urina - Hemácias',
    unit: 'uL',
    reference: '0–5',
    date1: '17/09/2025',
    value1: null,
    status1: 'N/A',
    date2: '02/12/2025',
    value2: 21,
    status2: 'Alto',
    observation: 'Hematúria microscópica',
    category: Category.URINE,
    trend: Trend.WORSENED
  },
  {
    id: 'urina_bacterias',
    name: 'Urina - Bactérias',
    unit: '',
    reference: 'Ausentes',
    date1: '17/09/2025',
    value1: null,
    status1: 'N/A',
    date2: '02/12/2025',
    value2: 'Numerosas',
    status2: 'Alto',
    observation: 'Presença significativa de bactérias',
    category: Category.URINE,
    trend: Trend.WORSENED
  }
];
